"""add applied flag to recommendations

Revision ID: 50174eb43d31
Revises: 577ebc531e98
Create Date: 2026-09-13 07:12:08.092868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50174eb43d31'
down_revision: Union[str, Sequence[str], None] = '577ebc531e98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recommendations', sa.Column('applied', sa.Boolean(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recommendations', 'applied')
    # ### end Alembic commands ###
